Repository IW4-GROUPE-AMG/Unsecure, pull requests merged in 2018-10, with the labels that each got.

#1 Add git template and gitignore
  .github/ISSUE_TEMPLATE/1_Bug_report.md
  .github/ISSUE_TEMPLATE/2_Feature_request.md
  .github/pull_request_template.md
  .gitignore
Labels: enhancement

#5 README & CONTRIBUTING
  CONTRIBUTING.md
  README.md
Labels: Configuration, enhancement

#6 Update Readme and add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  README.md
  src/UnsecureBundle/Controller/IndexController.php
Labels: Configuration
